version: '2'
services:
    front:
        build: ./frontend
        ports:
            - "8080:8080"
        depends_on:
            - "api"

    api:
        build: ./api
        ports:
            - "8181:8181"
        depends_on:
            - "mongo"

    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
#        volumes:
#            - data:/data/db
