version: '3'
services:
    api:
        build: ./api
        ports:
            - "8181:8181"
        depends_on:
            - "mongo"
    mongo:
        image: mongo
        restart: always
        ports:
            - 27017:27017
#        volumes:
#            - data:/data/db
